module.exports = {
  SUBSCRIPTION_TOKEN: "token",

  RESOURCE_ENERGY: "energy",
  RESOURCE_POWER: "power",

  RESOURCE_HYDROGEN: "H",
  RESOURCE_OXYGEN: "O",
  RESOURCE_UTRIUM: "U",
  RESOURCE_LEMERGIUM: "L",
  RESOURCE_KEANIUM: "K",
  RESOURCE_ZYNTHIUM: "Z",
  RESOURCE_CATALYST: "X",
  RESOURCE_GHODIUM: "G",

  RESOURCE_HYDROXIDE: "OH",
  RESOURCE_ZYNTHIUM_KEANITE: "ZK",
  RESOURCE_UTRIUM_LEMERGITE: "UL",

  RESOURCE_UTRIUM_HYDRIDE: "UH",
  RESOURCE_UTRIUM_OXIDE: "UO",
  RESOURCE_KEANIUM_HYDRIDE: "KH",
  RESOURCE_KEANIUM_OXIDE: "KO",
  RESOURCE_LEMERGIUM_HYDRIDE: "LH",
  RESOURCE_LEMERGIUM_OXIDE: "LO",
  RESOURCE_ZYNTHIUM_HYDRIDE: "ZH",
  RESOURCE_ZYNTHIUM_OXIDE: "ZO",
  RESOURCE_GHODIUM_HYDRIDE: "GH",
  RESOURCE_GHODIUM_OXIDE: "GO",

  RESOURCE_UTRIUM_ACID: "UH2O",
  RESOURCE_UTRIUM_ALKALIDE: "UHO2",
  RESOURCE_KEANIUM_ACID: "KH2O",
  RESOURCE_KEANIUM_ALKALIDE: "KHO2",
  RESOURCE_LEMERGIUM_ACID: "LH2O",
  RESOURCE_LEMERGIUM_ALKALIDE: "LHO2",
  RESOURCE_ZYNTHIUM_ACID: "ZH2O",
  RESOURCE_ZYNTHIUM_ALKALIDE: "ZHO2",
  RESOURCE_GHODIUM_ACID: "GH2O",
  RESOURCE_GHODIUM_ALKALIDE: "GHO2",

  RESOURCE_CATALYZED_UTRIUM_ACID: "XUH2O",
  RESOURCE_CATALYZED_UTRIUM_ALKALIDE: "XUHO2",
  RESOURCE_CATALYZED_KEANIUM_ACID: "XKH2O",
  RESOURCE_CATALYZED_KEANIUM_ALKALIDE: "XKHO2",
  RESOURCE_CATALYZED_LEMERGIUM_ACID: "XLH2O",
  RESOURCE_CATALYZED_LEMERGIUM_ALKALIDE: "XLHO2",
  RESOURCE_CATALYZED_ZYNTHIUM_ACID: "XZH2O",
  RESOURCE_CATALYZED_ZYNTHIUM_ALKALIDE: "XZHO2",
  RESOURCE_CATALYZED_GHODIUM_ACID: "XGH2O",
  RESOURCE_CATALYZED_GHODIUM_ALKALIDE: "XGHO2",


}

module.exports.RESOURCES_ALL = [module.exports.RESOURCE_ENERGY, module.exports.RESOURCE_POWER, module.exports.RESOURCE_HYDROGEN, module.exports.RESOURCE_OXYGEN, module.exports.RESOURCE_UTRIUM, module.exports.RESOURCE_KEANIUM, module.exports.RESOURCE_LEMERGIUM, module.exports.RESOURCE_ZYNTHIUM, module.exports.RESOURCE_CATALYST, module.exports.RESOURCE_GHODIUM, module.exports.RESOURCE_HYDROXIDE, module.exports.RESOURCE_ZYNTHIUM_KEANITE, module.exports.RESOURCE_UTRIUM_LEMERGITE, module.exports.RESOURCE_UTRIUM_HYDRIDE, module.exports.RESOURCE_UTRIUM_OXIDE, module.exports.RESOURCE_KEANIUM_HYDRIDE, module.exports.RESOURCE_KEANIUM_OXIDE, module.exports.RESOURCE_LEMERGIUM_HYDRIDE, module.exports.RESOURCE_LEMERGIUM_OXIDE, module.exports.RESOURCE_ZYNTHIUM_HYDRIDE, module.exports.RESOURCE_ZYNTHIUM_OXIDE, module.exports.RESOURCE_GHODIUM_HYDRIDE, module.exports.RESOURCE_GHODIUM_OXIDE, module.exports.RESOURCE_UTRIUM_ACID, module.exports.RESOURCE_UTRIUM_ALKALIDE, module.exports.RESOURCE_KEANIUM_ACID, module.exports.RESOURCE_KEANIUM_ALKALIDE, module.exports.RESOURCE_LEMERGIUM_ACID, module.exports.RESOURCE_LEMERGIUM_ALKALIDE, module.exports.RESOURCE_ZYNTHIUM_ACID, module.exports.RESOURCE_ZYNTHIUM_ALKALIDE, module.exports.RESOURCE_GHODIUM_ACID, module.exports.RESOURCE_GHODIUM_ALKALIDE, module.exports.RESOURCE_CATALYZED_UTRIUM_ACID, module.exports.RESOURCE_CATALYZED_UTRIUM_ALKALIDE, module.exports.RESOURCE_CATALYZED_KEANIUM_ACID, module.exports.RESOURCE_CATALYZED_KEANIUM_ALKALIDE, module.exports.RESOURCE_CATALYZED_LEMERGIUM_ACID, module.exports.RESOURCE_CATALYZED_LEMERGIUM_ALKALIDE, module.exports.RESOURCE_CATALYZED_ZYNTHIUM_ACID, module.exports.RESOURCE_CATALYZED_ZYNTHIUM_ALKALIDE, module.exports.RESOURCE_CATALYZED_GHODIUM_ACID, module.exports.RESOURCE_CATALYZED_GHODIUM_ALKALIDE];